### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by cauliyang** [ylab-hi/pxblat#44]
## 📆 **To-do**

- [x] parser gfclient result
- [x] parse gfserver query result
- [x] benchmarking multi connection and original version
- [x] test result with original version
- [x] fix build.py to build ssl, hts, maybe libuv when install with pip
- [x] add tool to conda channel
- [x] add tool to pip
- [x] change abort to throw exceptions
- [x] implement twobit2fa
- [ ] implement psl2sam
- [ ] implement WebUI

## 📖 Enhance Documentation 

- [x] Add comparable command line of BLAT 

## Add more tools as binding for current ucsc command line tools
